name: Playwright Tests
on: [pull_request, push]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.0
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright
        run: pnpm dlx playwright install --with-deps
      - name: Wait for Netlify Deploy
        uses: probablyup/wait-for-netlify-action@3.2.0
        id: waitForDeployment
        with:
          site_id: 'b652afbb-1dce-414a-bb18-a27b0b52c4e0' # See Settings > Site Details > General in the Netlify UI
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      - name: Run Playwright tests
        run: pnpm dlx playwright test
        env:
          # This might depend on your test-runner/language binding
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitForDeployment.outputs.url }}
